### PR TITLE
[ENTESB-8568]Unable to register security - ClassNotFoundException: Bo…

### PR DESCRIPTION
**Pull request by ffang**
…uncyCastleProvider

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I'm guessing this needs an updated Karaf release before it can be merged (i.e the build will break without it)?

**Comment by ffang** [comment]
@jamesnetherton Yes, it needs a [fix](https://github.com/jboss-fuse/karaf/commit/d9f7e38cdfe695e5711ce084f35829990bdacc8a) in Karaf

**Comment by jamesnetherton** [comment]
Ok, thanks. When the new release is available, please update the `fuse.version` property and we can get this merged. Same for the other karaf quickstart PRs.

**Comment by ffang** [comment]
@jamesnetherton yeah, hold this merge until we get a karaf build for FUSE 7.2

**Comment by jamesnetherton** [comment]
@ffang we should have a usable Karaf build now, right? If so, can you bump the `fuse.version` property (also for the other PRs) and we can merge.

**Comment by ffang** [comment]
@jamesnetherton yep, just bump fuse.version for all PRs, so should be ready to merge.

Thanks!

**Comment by jamesnetherton** [comment]
[merge]

**Pull request merged**
